### ISSUE TITLE
Got stuck with RepEnrich2

### ISSUE THREAD

**Issue by matwgmkw** [nskvir/RepEnrich2#26]
Hi. I got stuck while using RepEnrich2. Here is the error message I got. How can I fix it?

Software versions I used:
py-biopython/1.70_py27
bedtools/2.27.1
bowtie2/2.3.4.1
samtools 1.16.1
Python 2.7.13

Thanks.
Matthew

Preparing for analysis using RepEnrich2...
Conducting region sorting on unique mapping reads....
***** WARNING: File ./RepEnrich2_setup_hg38/repnames.bed has inconsistent naming convention for record:
chr1	10469	11447	TAR1

***** WARNING: File ./RepEnrich2_setup_hg38/repnames.bed has inconsistent naming convention for record:
chr1	10469	11447	TAR1

Identified 0 unique reads that mapped to repeats.
Processing repeat psuedogenomes...
sorting and combining the output for both read pairs...
completed ...
Writing and processing intermediate files...
Traceback (most recent call last):
  File "RepEnrich2.py", line 269, in <module>
    for data in import_text(sorted_ + os.path.sep + rep + '.txt', '\t'):
  File "RepEnrich2.py", line 64, in import_text
    skipinitialspace=True):
_csv.Error: line contains NULL byte

**Comment by matwgmkw** [comment]
I got the "regionsorter.txt" file with some data in it, but that is the only file I got after running RepEnrich2.

**Comment by matwgmkw** [comment]
Another question is if I downloaded the setup for the human genome from the dropbox link (https://www.dropbox.com/sh/ovf1t2gn5lvmyla/AADEPGgGMg-vjj8Gk-s76i6Ja?dl=0), do I still have to do the setup in step 2?

**Comment by nskvir** [comment]
Hi there, 

The setup folder is meant to save some time and should let you skip the setup step, but it seems like something might have been changed inside repnames.bed - maybe an extra tab or some white space was added to the line in question? If it still doesn't work after checking this, I would advise just starting from the first step and attaining fresh annotation files from UCSC table browser and running the setup yourself as opposed to using the dropbox folder.  That should give you a fresh setup folder that should work with whatever annotation you provide it.

Best,
Nick

**Comment by matwgmkw** [comment]
Hi Nick,
I am actually interested in the alpha-satellite repeats. Do you know what should I put In the "repclass does match with" field in UCSC table browser, is it "Satellite"? 

Also there are two files in repeat masters.org for hg38. One is "hg38 - Dec 2013 - RepeatMasker open-4.0.5 - Repeat Library 20140131" and the other one is "hg38 - Dec 2013 - RepeatMasker open-4.0.6 - Dfam 2.0". Which one should I download? Thank you very much!
-Matthew

**Comment by matwgmkw** [comment]
Also would this program works for the T2T genome as well? For example, can I download T2T .fa file and satellite repeat annotation from https://github.com/marbl/CHM13 and use these files to run the program?
Thanks.
Matthew
