### ISSUE TITLE
More questions

### ISSUE THREAD

**Issue by matwgmkw** [nskvir/RepEnrich2#27]
Hi Nick,
I am actually interested in the alpha-satellite repeats. Do you know what should I put In the "repclass does match with" field in UCSC table browser, is it "Satellite"? Looks like the program is building one separate bowtie2 index genome for each unique "Repeat_name" in the .bed file. Is that normal?

Also would this program works for the T2T genome as well? For example, can I download T2T .fa file and satellite repeat annotation from https://github.com/marbl/CHM13 and use these files to run the program?

Thank you very much!
-Matthew

**Comment by nskvir** [comment]
Hi Matthew, 
I would imagine they are probably labeled as Satellites, or something to that effect, though if you don't specify anything in that field you can just download the unfiltered annotation and look through yourself to verify what the labels are for the repeats of interest.  The index creation for each element is normal (the program creates 'pseudo-genomes' for each element to quantify counts across families and classes). Lastly, RepEnrich2 should work for whichever genome assembly you provide, including T2T, given that all the input files are formatted in the same ways referenced in the documentation.

Hope this helps!
Nick

**Comment by matwgmkw** [comment]
I see! So if the program creates a separate index for each of the elements, which one should I use for performing the Bowtie2 mapping  in step 3?
