### ISSUE TITLE
index for step 3

### ISSUE THREAD

**Issue by matwgmkw** [nskvir/RepEnrich2#28]
Hi Nick,

If the program creates a separate index for each of the elements, which one should I use for performing the Bowtie2 mapping in step 3? or anyone of the indexes is fine?

Thanks,
Matthew

**Comment by nskvir** [comment]
Hi Matthew, 
In step 3 you need to map your fastq reads to the regular genome (hg38, chm13, etc), not the assemblies of repetitive elements (check the example code for the syntax). These other assemblies you are looking at will be used by the program later to assign counts to multimapping reads when you run it - you shouldn't need to do anything with them manually. 

Best,
Nick
